const sampleData = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: '123456',
      role: 'admin',
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: '123456',
      role: 'user',
    },
  ],
  products: [
    {
      name: 'Polo Sporting Stretch Shirt',
      slug: 'polo-sporting-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Classic Polo style with modern comfort',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Polo',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: '/images/banner-1.jpg',
    },
    {
      name: 'Brooks Brothers Long Sleeved Shirt',
      slug: 'brooks-brothers-long-sleeved-shirt',
      category: "Men's Dress Shirts",
      description: 'Timeless style and premium comfort',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Brooks Brothers',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: '/images/banner-2.jpg',
    },
    {
      name: 'Tommy Hilfiger Classic Fit Dress Shirt',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Men's Dress Shirts",
      description: 'A perfect blend of sophistication and comfort',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Calvin Klein Slim Fit Stretch Shirt',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Men's Dress Shirts",
      description: 'Streamlined design with flexible stretch fabric',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Ralph Lauren Oxford Shirt',
      slug: 'polo-ralph-lauren-oxford-shirt',
      category: "Men's Dress Shirts",
      description: 'Iconic Polo design with refined oxford fabric',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Polo',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Polo Classic Pink Hoodie',
      slug: 'polo-classic-pink-hoodie',
      category: "Men's Sweatshirts",
      description: 'Soft, stylish, and perfect for laid-back days',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Polo',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Nike Air Max 270 Sneakers',
      slug: 'nike-air-max-270-sneakers',
      category: 'Sneakers',
      description: 'Maximum comfort with iconic Air Max cushioning',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 129.99,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 25,
      stock: 15,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Apple iPhone 15 Pro',
      slug: 'apple-iphone-15-pro',
      category: 'Electronics',
      description: 'Latest iPhone with advanced camera system and A17 Pro chip',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 999.99,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 42,
      stock: 12,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Samsung Galaxy S24 Ultra',
      slug: 'samsung-galaxy-s24-ultra',
      category: 'Electronics',
      description:
        'Premium Android flagship with S Pen and advanced AI features',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 1199.99,
      brand: 'Samsung',
      rating: 4.7,
      numReviews: 31,
      stock: 8,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Sony WH-1000XM5 Headphones',
      slug: 'sony-wh-1000xm5-headphones',
      category: 'Electronics',
      description:
        'Industry-leading noise cancellation with premium sound quality',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 349.99,
      brand: 'Sony',
      rating: 4.6,
      numReviews: 28,
      stock: 20,
      isFeatured: false,
      banner: null,
    },
    {
      name: "Levi's 501 Original Jeans",
      slug: 'levis-501-original-jeans',
      category: 'Jeans',
      description: 'Classic straight fit jeans with timeless style',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 69.99,
      brand: "Levi's",
      rating: 4.4,
      numReviews: 19,
      stock: 25,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Adidas Ultraboost 22',
      slug: 'adidas-ultraboost-22',
      category: 'Sneakers',
      description: 'Responsive cushioning with energy-returning Boost midsole',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 179.99,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 22,
      stock: 18,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'MacBook Pro 14-inch M3',
      slug: 'macbook-pro-14-inch-m3',
      category: 'Electronics',
      description: 'Powerful laptop with M3 chip for professionals',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 1999.99,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 15,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
    {
      name: 'Ray-Ban Aviator Classic',
      slug: 'ray-ban-aviator-classic',
      category: 'Accessories',
      description:
        'Timeless aviator sunglasses with gold frame and green lenses',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 154.99,
      brand: 'Ray-Ban',
      rating: 4.3,
      numReviews: 11,
      stock: 30,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Casio G-Shock DW5600',
      slug: 'casio-g-shock-dw5600',
      category: 'Accessories',
      description:
        'Durable digital watch with shock resistance and water resistance',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 49.99,
      brand: 'Casio',
      rating: 4.2,
      numReviews: 8,
      stock: 35,
      isFeatured: false,
      banner: null,
    },
  ],
};

export default sampleData;
